# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 09:32
from __future__ import unicode_literals

import abstractApp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('event_name', models.CharField(max_length=20)),
                ('event_description', models.CharField(max_length=150)),
                ('coorX', models.CharField(max_length=10)),
                ('coorY', models.CharField(max_length=10)),
                ('reward', models.CharField(max_length=70)),
            ],
            options={
                'verbose_name_plural': 'Crear evento',
            },
        ),
        migrations.CreateModel(
            name='EventoLimitado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ini_date', models.DateTimeField(blank=True, validators=[abstractApp.models.fechaIniMayorActual])),
                ('exp_date', models.DateTimeField(blank=True, validators=[abstractApp.models.fechaExpMayorIni])),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='abstractApp.Evento')),
            ],
            options={
                'verbose_name_plural': 'Convertir evento en evento limitado',
            },
        ),
        migrations.CreateModel(
            name='EventoParada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='abstractApp.Evento')),
            ],
            options={
                'verbose_name_plural': 'Convertir evento en evento parada',
            },
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Imagenes',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('user_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Modificar usuario',
            },
        ),
        migrations.CreateModel(
            name='UsuarioEventoLimitado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abstractApp.EventoLimitado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abstractApp.Usuario')),
            ],
            options={
                'verbose_name_plural': 'Inscribir usuario a evento limitado',
            },
        ),
        migrations.CreateModel(
            name='UsuarioEventoParada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_use', models.DateTimeField(blank=True)),
                ('cooldown', models.TimeField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abstractApp.EventoParada')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abstractApp.Usuario')),
            ],
            options={
                'verbose_name_plural': 'Inscribir usuario a evento parada',
            },
        ),
        migrations.AlterUniqueTogether(
            name='usuarioeventoparada',
            unique_together=set([('user', 'event')]),
        ),
        migrations.AlterUniqueTogether(
            name='usuarioeventolimitado',
            unique_together=set([('user', 'event')]),
        ),
    ]
