# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstractApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='coorX',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='coorY',
        ),
        migrations.AddField(
            model_name='evento',
            name='latitud',
            field=models.CharField(default=1, max_length=10, verbose_name='Latitud'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='longitud',
            field=models.CharField(default=1, max_length=10, verbose_name='Longitud'),
            preserve_default=False,
        ),
    ]
