# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstractApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='event_type',
            field=models.CharField(choices=[('Parada', 'Limitado')], default='1', max_length=10),
        ),
    ]
