# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstractApp', '0002_evento_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='event_type',
            field=models.CharField(choices=[('Parada', 'Limitado')], default='Parada', max_length=10),
        ),
    ]
