# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 13:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstractApp', '0003_usuarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='eventos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('coorX', models.CharField(max_length=10)),
                ('coorY', models.CharField(max_length=10)),
                ('recompensa', models.CharField(max_length=70)),
                ('disponible', models.BooleanField(verbose_name=True)),
                ('start', models.DateField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='personas',
        ),
    ]
