# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 10:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abstractApp', '0003_auto_20170415_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='event_type',
        ),
    ]
