# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstractApp', '0004_remove_evento_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioeventoparada',
            name='cooldown',
            field=models.DurationField(blank=True),
        ),
    ]
