# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 13:47
from __future__ import unicode_literals

import abstractApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstractApp', '0005_auto_20170415_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventolimitado',
            name='exp_date',
            field=models.DateTimeField(validators=[abstractApp.models.fechaExpMayorIni]),
        ),
        migrations.AlterField(
            model_name='eventolimitado',
            name='ini_date',
            field=models.DateTimeField(validators=[abstractApp.models.fechaIniMayorActual]),
        ),
        migrations.AlterField(
            model_name='usuarioeventoparada',
            name='cooldown',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='usuarioeventoparada',
            name='last_use',
            field=models.DateTimeField(),
        ),
    ]
