# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 14:34
from __future__ import unicode_literals

import abstractApp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abstractApp', '0006_auto_20170415_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recompensa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_name', models.CharField(max_length=70, verbose_name='Recompensa')),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='evento',
            name='brand',
            field=models.CharField(max_length=50, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='coorX',
            field=models.CharField(max_length=10, verbose_name='Coordenada X'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='coorY',
            field=models.CharField(max_length=10, verbose_name='Coordenada Y'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='event_description',
            field=models.CharField(max_length=150, verbose_name='Descripcion del evento'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='event_name',
            field=models.CharField(max_length=20, verbose_name='Nombre del evento'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='reward',
            field=models.CharField(max_length=70, verbose_name='Recompensa'),
        ),
        migrations.AlterField(
            model_name='eventolimitado',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='abstractApp.Evento', verbose_name='Evento'),
        ),
        migrations.AlterField(
            model_name='eventolimitado',
            name='exp_date',
            field=models.DateTimeField(validators=[abstractApp.models.fechaExpMayorIni], verbose_name='Fecha de fin'),
        ),
        migrations.AlterField(
            model_name='eventolimitado',
            name='ini_date',
            field=models.DateTimeField(validators=[abstractApp.models.fechaIniMayorActual], verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='eventoparada',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='abstractApp.Evento', verbose_name='Evento'),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='img',
            field=models.ImageField(upload_to='', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='usuarioeventolimitado',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abstractApp.EventoLimitado', verbose_name='Evento'),
        ),
        migrations.AlterField(
            model_name='usuarioeventolimitado',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abstractApp.Usuario', verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='usuarioeventoparada',
            name='cooldown',
            field=models.DurationField(verbose_name='Tiempo de espera'),
        ),
        migrations.AlterField(
            model_name='usuarioeventoparada',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abstractApp.EventoParada', verbose_name='Evento'),
        ),
        migrations.AlterField(
            model_name='usuarioeventoparada',
            name='last_use',
            field=models.DateTimeField(verbose_name='Ultima vez usado'),
        ),
        migrations.AlterField(
            model_name='usuarioeventoparada',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abstractApp.Usuario', verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='recompensa',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abstractApp.Usuario', verbose_name='Usuario'),
        ),
    ]
